vim.cmd('runtime! ftplugin/yaml.lua')

-- local surround_config = require('nvim-surround.config')
-- require('nvim-surround').buffer_setup({
--   surrounds = {
--     -- The below works but not useful
--     V = {
--       ---@diagnostic disable-next-line: assign-type-mismatch
--       add = { "{{ $", " }}" },
--       find = function()
--         return surround_config.get_selection({ pattern = '{{ ?%$[^}]* ?}}' })
--       end,
--       ---@diagnostic disable-next-line: assign-type-mismatch
--       delete = '^(....)().-( ?..)()$',
--       change = {
--         ---@diagnostic disable-next-line: assign-type-mismatch
--         target = '({{ %$)()[^}]*( }})()',
--       },
--     },
--   },
-- })
