# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = "d"
run = "remove --permanently"
desc = "Permanently delete selected files"

[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = '''
	shell 'ya emit cd "$(git rev-parse --show-toplevel)"'
'''

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "<A-j>"
run = "seek 5"
desc = "Scroll preview down"

[[mgr.prepend_keymap]]
on = "<A-k>"
run = "seek -5"
desc = "Scroll preview up"

[[mgr.prepend_keymap]]
on = "<A-p>"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview pane"

[[mgr.prepend_keymap]]
on = "<A-P>"
run = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"
