#!/bin/bash

set -eo pipefail

editor="${EDITOR:-vim}"
taskcmd="${TASKNOTE_TASKCMD:-task}"
viewer="${TASKNOTE_VIEWER:-cat}"
shell=/bin/bash
ext="${TASKNOTE_EXT:-.todo.md}"

note_dir="${HOME}/.local/share/taskopen/notes"
sub_cmd="edit"

usage() {
  echo "Usage:"
  echo "  New/Edit note: $0 <UUID>"
  echo "  View note:     $0 -v <UUID>"
  echo "  Prune notes:   $0 -p"
}

while getopts "hvp" opt; do
  case $opt in
  v)
    shift $((OPTIND - 1))
    sub_cmd="view"
    ;;
  p)
    shift $((OPTIND - 1))
    sub_cmd="prune"
    ;;
  h)
    shift $((OPTIND - 1))
    usage
    exit 0
    ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    usage
    exit 1
    ;;
  esac
done

if [ "$sub_cmd" != "prune" ] && [ $# -ne 1 ]; then
  echo "Invalid number of arguments."
  usage
  exit 1
fi

if [ ! -e $note_dir ]; then
  echo "Notes directory '$note_dir' does not exist."
  echo -n "Shall I create it (y/N)? "
  read answer
  if [ $answer == "y" ]; then
    mkdir -p $note_dir
    echo "'$note_dir' has been created."
  else
    echo "Did NOT create $note_dir. Exiting."
    exit 1
  fi
fi

task_uuid=$1
task_id=$($taskcmd $task_uuid ids)
file="$note_dir/$task_uuid$ext"

view() {
  if [ -f $file ]; then
    $shell -c "$viewer $file"
  else
    echo "File not found"
    exit 1
  fi
}

edit() {
  file_exists=false
  $shell -c "$editor $file"

  # Return if file was not created
  if [ -f $file ]; then
    file_exists=true
  fi

  annotation_symbol="Notes"
  annotation_count=$($shell -c "$taskcmd _get ${task_id}.annotations.count")
  has_note=false
  if [ $annotation_count -gt 0 ]; then
    for i in $(seq 1 $annotation_count); do
      task _get ${task_id}.annotations.${i}.description | grep -q "$annotation_symbol" && has_note=true
    done
  fi

  # Annotate or denotate based on presence of Note annotation and file
  if $has_note; then
    if ! $file_exists; then
      $shell -c "$taskcmd $task_id denotate '$annotation_symbol'"
    fi
  else
    if $file_exists; then
      $shell -c "$taskcmd $task_id annotate '$annotation_symbol'"
    fi
  fi
}

prune() {
  active_uuids=$(task -DELETED uuids)

  if [ -z "$active_uuids" ]; then
    echo -n "No active tasks found. Deleting all notes? (y/N): "
    read answer
    if [ $answer == "y" ]; then
      rm --force "$note_dir"/*"$ext"
      echo "All notes have been deleted."
    else
      echo "Deletion aborted."
    fi
    exit 0
  fi

  deleted=false
  for note in "$note_dir"/*"$ext"; do
    note_uuid=$(basename "$note" $ext)

    if [[ ! " ${active_uuids} " =~ " $note_uuid " ]]; then
      deleted=true
      rm --force "$note"
    fi
  done

  if ! $deleted; then
    echo "No notes to prune."
  else
    echo "Pruning complete."
  fi
}

case $sub_cmd in
edit)
  edit
  ;;
view)
  view
  ;;
prune)
  prune
  ;;
*)
  echo "Unknown sub-command: $sub_cmd"
  exit 1
  ;;
esac

exit 0
