#!/bin/bash

set -eo pipefail

editor="${EDITOR:-vim}"
taskcmd="${TASKNOTE_TASKCMD:-task}"
viewer="${TASKNOTE_VIEWER:-cat}"
shell=/bin/bash
ext="${TASKNOTE_EXT:-.md}"

note_dir="${HOME}/.local/share/taskopen/notes"

# Display usage if task number not supplied on cli
if [ $# -lt 1 -o $# -gt 2 ]; then
  echo "Usage:"
  echo "  New/Edit note: $0 <id>"
  echo "  View note:     $0 <id> v"
  exit 1
fi

# Check for existence of $note_dir
if [ ! -e $note_dir ]; then
  echo "Notes directory '$note_dir' does not exist."
  echo -n "Shall I create it (y/n)? "
  read answer
  if [ $answer == "y" ]; then
    echo "Creating '$note_dir'."
    mkdir -p $note_dir
  else
    echo "Did NOT create $note_dir. Exiting."
    exit 1
  fi
fi

task_uuid=$1
task_id=$($taskcmd $task_uuid ids)
file="$note_dir/$task_uuid$ext"

view() {
  if [ -f $file ]; then
    $shell -c "$viewer $file"
  else
    echo "File not found"
    exit 1
  fi
}

edit() {
  file_exists=false
  $shell -c "$editor $file"

  # Return if file was not created
  if [ -f $file ]; then
    file_exists=true
  fi

  annotation_symbol="Notes"
  annotation_count=$($shell -c "$taskcmd _get ${task_id}.annotations.count")
  has_note=false
  if [ $annotation_count -gt 0 ]; then
    for i in $(seq 1 $annotation_count); do
      task _get ${task_id}.annotations.${i}.description | grep -q "$annotation_symbol" && has_note=true
    done
  fi

  # Annotate or denotate based on presence of Note annotation and file
  if $has_note; then
    if ! $file_exists; then
      $shell -c "$taskcmd $task_id denotate '$annotation_symbol'"
    fi
  else
    if $file_exists; then
      $shell -c "$taskcmd $task_id annotate '$annotation_symbol'"
    fi
  fi
}

if [ $# -gt 1 ]; then
  view
else
  edit
fi

exit 0
