version: '3.9'
services:
  ide:
    environment:
      - CGO_ENABLED=${CGO_ENABLED:-0}
    build:
      args:
        - GO_VERSION
        - GO_ARCH
    volumes:
      - type: volume
        source: gopath
        target: /home/mojito/go
volumes:
  gopath:
    # external to prevent accidental deletion (but prone to `prune` command)
    external: true
