version: '3.9'
services:
  base:
    build:
      context: ctx
      args:
        - USER=mojito
        - COMPOSE_VERSION=${COMPOSE_VERSION:?set value in .env file}
        - GIT_USER_NAME=${GIT_USER_NAME:?set value in .env file}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL:?set value in .env file}
        - GIT_HUB_SSH_KEY=${GIT_HUB_SSH_KEY:?set value in .env file}
    volumes:
      # Be aware if the volume which was previously created exists.
      # It covers up files copied or created during build. In such case,
      # delete the volume and run `docker-compose up` again.
      - type: volume
        source: home
        target: /home/mojito
      # bind socket file so that the same docker can be used inside containers
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ${HOST_HOME:?}/workspace
        target: /home/mojito/workspace
      - type: bind
        source: ${HOST_HOME:?}/.ssh
        target: /home/mojito/.ssh
volumes:
  home:
