version: '3.9'
services:
  ide:
    environment:
      - GIT_HUB_SSH_KEY
      - DISPLAY # setting the same value as WSL works in container as well
      - COMPOSE_PROJECT_NAME # referring this inside container tells you which container you are in
    build:
      context: ./${COMPOSE_PROJECT_NAME:?}/ctx
      args:
        - IMAGE_TAG
        - USER=mojito
        - CPU_ARCH
    volumes:
      # Be aware if the volume which was previously created exists.
      # It covers up files copied or created during build. In such case,
      # delete the volume and run `docker-compose up` again.
      - type: volume
        source: home
        target: /home/mojito
      - type: volume
        source: vim-plugin
        target: /home/mojito/.vim/bundle
      # bind socket file so that the same docker can be used inside containers
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # Binding below two timezone file sync timezone of containers to the host machine
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
      - type: bind
        source: ${HOST_HOME:?}
        target: /home/mojito/hosthome
      # Bind volume `workspace` direcory instead of symlinking so that relative
      # path of bind volume inside IDE container does not result in error
      - type: bind
        source: ${HOST_HOME:?}/workspace
        target: /home/mojito/workspace
    network_mode: "host"
volumes:
  home:
  vim-plugin:
    external: true
